// ═══════════════════════════════════════════════════════════════
// official-presets.js — BOARDGAMEZ OS v2.0
// Todos los presets revisados con el nuevo modelo:
// - agileTurnButtons para acciones del turno
// - gamePhases con scope:'turn' vs scope:'round' correctos
// - phaseChecklist vinculados a fases correctas
// - objectControlScope correcto por juego
// ═══════════════════════════════════════════════════════════════
window.OFFICIAL_PRESETS = {

  strike: {
    id:'strike', order:1, name:'Strike', emoji:'🎳', color:'#FF6B35',
    category:'survival', complexity:'low',
    validates:['turns','elimination','lives'],
    valueAdd:['Auto-eliminación por rondas','Sin puntos = máxima agilidad','Último en pie gana'],
    config:{
      name:'Strike', emoji:'🎳', type:'individual',
      minPlayers:3, maxPlayers:12,
      useRounds:true, rounds:'libre', roundClose:'auto',
      useTurns:false,
      victoryMode:'elimination',
      registers:['lives'],
      playMode:'minimal',
      playObjects:[],
      objectControlScope:'host',
      useFlowAssistance:false,
    }
  },

  cubilete: {
    id:'cubilete', order:2, name:'Cubilete', emoji:'🎲', color:'#FFD447',
    category:'dice_party', complexity:'medium',
    validates:['turns','lives','tools'],
    valueAdd:['5 vidas por jugador','Dados integrados','Perder vida = un turno'],
    config:{
      name:'Cubilete', emoji:'🎲', type:'individual',
      minPlayers:2, maxPlayers:8,
      useRounds:true, rounds:'libre', roundClose:'manual',
      useTurns:true, turnOrder:'rotative', useFirstPlayerToken:false,
      victoryMode:'lives', primaryUnit:'lives',
      registers:['lives'],
      playMode:'minimal',
      playObjects:['dice_tool'],
      objectControlScope:'all',
      useTools:true, tools:['dice'], diceType:'d6',
      useFlowAssistance:true,
      turnAssistMode:'agile',
      agileTurnButtons:[
        { label:'Perdí una vida', icon:'❤️', effect:'log_event' },
      ],
      gamePhases:[
        { id:'roll_dice', label:'Tirar dados', order:1, scope:'turn', owner:'player',
          trigger:'turn_start', description:'Tira los dados y aplica el resultado' },
      ],
      phaseChecklist:[
        { id:'apply_result', label:'¿Aplicaste el resultado al marcador?',
          phaseId:'roll_dice', required:false, autoReset:'turn', visibleTo:'all' },
      ],
    }
  },

  flip7: {
    id:'flip7', order:3, name:'Flip 7', emoji:'🃏', color:'#FF3B5C',
    category:'card_game', complexity:'low',
    validates:['turns','points','card_game'],
    valueAdd:['Voltear cartas hasta 7 sin pasarse','Captura de puntos por ronda','Turnos rápidos'],
    config:{
      name:'Flip 7', emoji:'🃏', type:'individual',
      minPlayers:2, maxPlayers:6,
      useRounds:true, rounds:'libre', roundClose:'manual',
      useTurns:true, turnOrder:'rotative', useFirstPlayerToken:false,
      victoryMode:'points', pointsWinMode:'most',
      registers:['points'],
      playMode:'minimal',
      playObjects:['score_input'],
      scoreInputLabel:'Puntos de ronda',
      scoreInputTarget:'points',
      scoreInputAllowNegative:false,
      scoreInputQuickValues:[1,2,3,5,7,10],
      objectControlScope:'self',
      useFlowAssistance:true,
      turnAssistMode:'agile',
      agileTurnButtons:[
        { label:'Voltear carta', icon:'🃏', effect:'log_event' },
        { label:'Me pasé (OUT)', icon:'💀', effect:'log_event' },
      ],
    }
  },

  uno: {
    id:'uno', order:4, name:'UNO', emoji:'🟥', color:'#FF3B5C',
    category:'card_game', complexity:'low',
    validates:['turns','points','penalties'],
    valueAdd:['Puntos por cartas en mano','Penalizaciones','Turnos con acciones especiales'],
    config:{
      name:'UNO', emoji:'🟥', type:'individual',
      minPlayers:2, maxPlayers:10,
      useRounds:true, rounds:'libre', roundClose:'manual',
      useTurns:true, turnOrder:'rotative', useFirstPlayerToken:false,
      victoryMode:'points', pointsWinMode:'least',
      registers:['points'],
      playMode:'minimal',
      playObjects:['score_input'],
      scoreInputLabel:'Cartas en mano (pts)',
      scoreInputTarget:'points',
      scoreInputAllowNegative:false,
      scoreInputQuickValues:[0,1,2,5,10,20,50],
      objectControlScope:'self',
      useFlowAssistance:true,
      turnAssistMode:'agile',
      agileTurnButtons:[
        { label:'¡UNO!', icon:'🟥', effect:'log_event' },
        { label:'+2 / +4', icon:'🃏', effect:'log_event' },
      ],
      gamePhases:[
        { id:'play_card', label:'Jugar carta', order:1, scope:'turn', owner:'player',
          trigger:'turn_start', description:'Juega una carta o toma del mazo' },
      ],
    }
  },

  noThanks: {
    id:'no_thanks', order:5, name:'No Thanks', emoji:'🚫', color:'#4A90FF',
    category:'card_game', complexity:'low',
    validates:['turns','points','tokens'],
    valueAdd:['Menos puntos gana','Fichas como escudo','Decisiones rápidas'],
    config:{
      name:'No Thanks', emoji:'🚫', type:'individual',
      minPlayers:3, maxPlayers:7,
      useRounds:false,
      useTurns:true, turnOrder:'rotative', useFirstPlayerToken:false,
      victoryMode:'points', pointsWinMode:'least',
      registers:['points'],
      playMode:'minimal',
      playObjects:['score_input'],
      scoreInputLabel:'Puntos finales',
      scoreInputTarget:'points',
      scoreInputAllowNegative:false,
      objectControlScope:'self',
      useFlowAssistance:true,
      turnAssistMode:'agile',
      agileTurnButtons:[
        { label:'Tomar carta', icon:'🃏', effect:'log_event' },
        { label:'No Thanks 🪙', icon:'🚫', effect:'log_event' },
      ],
    }
  },

  sushiGo: {
    id:'sushi_go', order:6, name:'Sushi Go', emoji:'🍣', color:'#FF6B6B',
    category:'card_drafting', complexity:'low',
    validates:['rounds','points','simultaneous'],
    valueAdd:['Puntos por ronda','Draft simultáneo','Scoring al final de cada ronda'],
    config:{
      name:'Sushi Go', emoji:'🍣', type:'individual',
      minPlayers:2, maxPlayers:5,
      useRounds:true, rounds:3, roundClose:'manual',
      useTurns:false,
      victoryMode:'points', pointsWinMode:'most',
      registers:['points'],
      playMode:'minimal',
      playObjects:['score_input'],
      scoreInputLabel:'Puntos de ronda',
      scoreInputTarget:'points',
      scoreInputAllowNegative:false,
      scoreInputQuickValues:[1,2,3,5,6,10,12],
      objectControlScope:'self',
      useFlowAssistance:true,
      turnAssistMode:'regulatory',
      roundPhasesEnabled:true,
      gamePhases:[
        { id:'draft', label:'Draft simultáneo', order:1, scope:'round', owner:'all',
          trigger:'manual', description:'Todos eligen una carta y pasan la mano' },
        { id:'scoring', label:'Contar puntos', order:2, scope:'round', owner:'host',
          trigger:'manual', description:'Calcular puntos de nigiri, tempura, sashimi...' },
        { id:'pudding', label:'Pudding al final', order:3, scope:'round', owner:'host',
          trigger:'manual', description:'Solo en la ronda 3: sumar/restar puddings' },
      ],
      phaseChecklist:[
        { id:'all_picked', label:'¿Todos eligieron su carta?',
          phaseId:'draft', required:true, autoReset:'round', visibleTo:'host' },
        { id:'scores_counted', label:'¿Se contaron todos los puntos?',
          phaseId:'scoring', required:true, autoReset:'round', visibleTo:'host' },
      ],
    }
  },

  kingOfTokyo: {
    id:'king_of_tokyo', order:7, name:'King of Tokyo', emoji:'👾', color:'#00FF9D',
    category:'dice_combat', complexity:'medium',
    validates:['turns','lives','points','dice','combat'],
    valueAdd:['10 vidas + energía','Dados especiales','Entrar/salir de Tokyo'],
    config:{
      name:'King of Tokyo', emoji:'👾', type:'individual',
      minPlayers:2, maxPlayers:6,
      useRounds:true, rounds:'libre', roundClose:'manual',
      useTurns:true, turnOrder:'rotative', useFirstPlayerToken:false,
      victoryMode:'points', pointsWinMode:'reach_x', targetScore:20,
      registers:['points','lives'],
      playMode:'enhanced',
      playObjects:['score_input','dice_tool'],
      scoreInputLabel:'Puntos / Daño',
      scoreInputTarget:'points',
      scoreInputAllowNegative:true,
      objectControlScope:'all',
      useTools:true, tools:['dice'], diceType:'d6',
      useFlowAssistance:true,
      turnAssistMode:'regulatory',
      agileTurnButtons:[
        { label:'Daño recibido', icon:'💀', effect:'log_event' },
      ],
      gamePhases:[
        { id:'roll_phase', label:'Tirar dados (hasta 3 veces)', order:1, scope:'turn',
          owner:'player', trigger:'turn_start', description:'Tira 6 dados, conserva y re-tira hasta 3 veces' },
        { id:'resolve_phase', label:'Resolver dados', order:2, scope:'turn',
          owner:'player', trigger:'manual', description:'Aplica rayos, corazones, garras y puntos' },
      ],
      externalEntities:[
        { id:'tokyo_holder', label:'Tokyo ocupado por', icon:'🏙️',
          entityType:'token', stateType:'holder', defaultState:'nadie', visibleTo:'all' },
      ],
    }
  },

  bang: {
    id:'bang', order:8, name:'Bang!', emoji:'🔫', color:'#B7FF3C',
    category:'social_deduction', complexity:'medium',
    validates:['turns','lives','roles','tools'],
    valueAdd:['Roles ocultos','4-5 vidas por rol','Dados especiales Dodge City (opcional)'],
    config:{
      name:'Bang!', emoji:'🔫', type:'individual',
      minPlayers:4, maxPlayers:7,
      useRounds:true, rounds:'libre', roundClose:'manual',
      useTurns:true, turnOrder:'rotative', useFirstPlayerToken:false,
      victoryMode:'elimination',
      registers:['lives'],
      playMode:'enhanced',
      playObjects:['dice_tool'],
      objectControlScope:'host',
      useTools:true, tools:['dice'],
      useFlowAssistance:true,
      turnAssistMode:'regulatory',
      gamePhases:[
        { id:'draw', label:'Robar 2 cartas', order:1, scope:'turn',
          owner:'player', trigger:'turn_start', description:'Roba 2 cartas del mazo' },
        { id:'play', label:'Jugar cartas', order:2, scope:'turn',
          owner:'player', trigger:'manual', description:'Juega las cartas que quieras' },
        { id:'discard', label:'Descartar exceso', order:3, scope:'turn',
          owner:'player', trigger:'manual', description:'Descarta hasta = número de vidas' },
      ],
      phaseChecklist:[
        { id:'discard_check', label:'¿Cartas en mano ≤ vidas?',
          phaseId:'discard', required:true, autoReset:'turn', visibleTo:'all' },
      ],
      externalEntities:[
        { id:'sheriff', label:'Sheriff', icon:'⭐', entityType:'role',
          stateType:'holder', defaultState:'manual', visibleTo:'all' },
      ],
    }
  },

  loveLetter: {
    id:'love_letter', order:9, name:'Love Letter', emoji:'💌', color:'#FF6B6B',
    category:'card_game', complexity:'low',
    validates:['turns','wins','card_game'],
    valueAdd:['Ganar rondas = tokens de afecto','Eliminación dentro de ronda','Cartas de 1 en mano'],
    config:{
      name:'Love Letter', emoji:'💌', type:'individual',
      minPlayers:2, maxPlayers:6,
      useRounds:true, rounds:'libre', roundClose:'manual',
      useTurns:true, turnOrder:'rotative', useFirstPlayerToken:false,
      victoryMode:'wins', winsTarget:4,
      registers:['wins'],
      playMode:'minimal',
      playObjects:[],
      objectControlScope:'host',
      useFlowAssistance:true,
      turnAssistMode:'agile',
      agileTurnButtons:[
        { label:'Ganar ronda 💌', icon:'🏆', effect:'add_win' },
        { label:'Eliminado 💔', icon:'💀', effect:'log_event' },
      ],
      gamePhases:[
        { id:'draw_play', label:'Robar y jugar', order:1, scope:'turn',
          owner:'player', trigger:'turn_start', description:'Roba una carta y juega una' },
      ],
    }
  },

  coup: {
    id:'coup', order:10, name:'Coup', emoji:'👑', color:'#9B5DE5',
    category:'social_deduction', complexity:'medium',
    validates:['turns','elimination','coins'],
    valueAdd:['2 influencias por jugador','Monedas como recurso','Bluffing y eliminación'],
    config:{
      name:'Coup', emoji:'👑', type:'individual',
      minPlayers:2, maxPlayers:6,
      useRounds:true, rounds:'libre', roundClose:'manual',
      useTurns:true, turnOrder:'rotative', useFirstPlayerToken:false,
      victoryMode:'elimination',
      registers:['lives','coins'],
      playMode:'enhanced',
      playObjects:['score_input'],
      scoreInputLabel:'Ajustar monedas',
      scoreInputTarget:'coins',
      scoreInputAllowNegative:true,
      scoreInputQuickValues:[1,2,3,7,-1,-2,-3],
      objectControlScope:'host',
      useFlowAssistance:true,
      turnAssistMode:'agile',
      agileTurnButtons:[
        { label:'Perder influencia', icon:'💀', effect:'log_event' },
      ],
    }
  },

  azul: {
    id:'azul', order:11, name:'Azul', emoji:'🟦', color:'#4A90FF',
    category:'tile_scoring', complexity:'medium',
    validates:['rounds','points','phases','checklist'],
    valueAdd:['3 fases de ronda','Checklist de cierre','Scoring complejo con bonus'],
    config:{
      name:'Azul', emoji:'🟦', type:'individual',
      minPlayers:2, maxPlayers:4,
      useRounds:true, rounds:'libre', roundClose:'manual',
      useTurns:false,
      victoryMode:'points', pointsWinMode:'most',
      registers:['points'],
      playMode:'enhanced',
      playObjects:['score_input'],
      scoreInputLabel:'Puntos de ronda',
      scoreInputTarget:'points',
      scoreInputAllowNegative:true,
      scoreInputQuickValues:[1,2,3,5,7,10,-1,-2,-5],
      objectControlScope:'self',
      useFlowAssistance:true,
      turnAssistMode:'regulatory',
      roundPhasesEnabled:true,
      gamePhases:[
        { id:'factory_offer', label:'Oferta de fábricas', order:1, scope:'round',
          owner:'all', trigger:'manual',
          description:'Tomar azulejos de fábrica o centro' },
        { id:'wall_tiling', label:'Mosaico / pared', order:2, scope:'round',
          owner:'all', trigger:'manual',
          description:'Colocar azulejos en la pared y anotar' },
        { id:'cleanup', label:'Limpieza y primer jugador', order:3, scope:'round',
          owner:'host', trigger:'manual',
          description:'Limpiar líneas de patrón, penalización piso, pasar ficha' },
      ],
      phaseChecklist:[
        { id:'penalty_applied', label:'Aplicar penalización del piso (-1,-2,-3...)',
          phaseId:'wall_tiling', required:true, autoReset:'round', visibleTo:'all' },
        { id:'bonus_check', label:'¿Alguien completó fila horizontal? (+2)',
          phaseId:'cleanup', required:false, autoReset:'round', visibleTo:'host' },
        { id:'end_game_check', label:'¿Alguien completó una fila completa? (fin de partida)',
          phaseId:'cleanup', required:true, autoReset:'round', visibleTo:'host' },
        { id:'final_bonus', label:'Si terminó: aplicar bonus final (columna/color/diagonal)',
          phaseId:'cleanup', required:false, autoReset:'round', visibleTo:'host' },
      ],
      externalEntities:[
        { id:'first_player_tile', label:'Ficha primer jugador', icon:'🎯',
          entityType:'token', stateType:'holder', defaultState:'centro', visibleTo:'all' },
        { id:'tile_bag', label:'Bolsa de azulejos', icon:'🎒',
          entityType:'resource', stateType:'status', defaultState:'llena', visibleTo:'host' },
      ],
    }
  },

  yahtzee: {
    id:'yahtzee', order:12, name:'Yahtzee', emoji:'🎰', color:'#FFD447',
    category:'dice_scoring', complexity:'low',
    validates:['turns','points','dice'],
    valueAdd:['Hasta 3 tiradas por turno','Scoring por combinaciones','Sin eliminación'],
    config:{
      name:'Yahtzee', emoji:'🎰', type:'individual',
      minPlayers:1, maxPlayers:6,
      useRounds:true, rounds:13, roundClose:'auto',
      useTurns:true, turnOrder:'rotative', useFirstPlayerToken:false,
      victoryMode:'points', pointsWinMode:'most',
      registers:['points'],
      playMode:'minimal',
      playObjects:['score_input','dice_tool'],
      scoreInputLabel:'Puntos de combinación',
      scoreInputTarget:'points',
      scoreInputAllowNegative:false,
      scoreInputQuickValues:[0,15,20,25,30,35,40,50],
      objectControlScope:'self',
      useTools:true, tools:['dice'], diceType:'d6',
      useFlowAssistance:true,
      turnAssistMode:'regulatory',
      gamePhases:[
        { id:'roll1', label:'1ª tirada', order:1, scope:'turn',
          owner:'player', trigger:'turn_start', description:'Tira los 5 dados' },
        { id:'roll2', label:'2ª tirada (opcional)', order:2, scope:'turn',
          owner:'player', trigger:'manual', description:'Conserva y vuelve a tirar' },
        { id:'roll3', label:'3ª tirada (opcional)', order:3, scope:'turn',
          owner:'player', trigger:'manual', description:'Última oportunidad' },
        { id:'score', label:'Anotar categoría', order:4, scope:'turn',
          owner:'player', trigger:'manual', description:'Elige dónde anotar los puntos' },
      ],
    }
  },

  deadOfWinter: {
    id:'dead_of_winter', order:13, name:'Dead of Winter', emoji:'❄️', color:'#B0C4DE',
    category:'cooperative_assist', complexity:'high',
    validates:['rounds','phases','checklist','entities','cooperative'],
    valueAdd:['Asistente cooperativo','Fase de crisis','Checklist de cierre de ronda','Entidades: moral y colonia'],
    config:{
      name:'Dead of Winter', emoji:'❄️', type:'cooperative',
      cooperativeTeamName:'La Colonia',
      minPlayers:2, maxPlayers:5,
      useRounds:true, rounds:'libre', roundClose:'manual',
      useTurns:true, turnOrder:'rotative', useFirstPlayerToken:false,
      victoryMode:'manual', manualWinMode:'host_end',
      registers:[],
      playMode:'enhanced',
      playObjects:[],
      objectControlScope:'all',
      useFlowAssistance:true,
      turnAssistMode:'agile',
      agileTurnButtons:[
        { label:'Acción realizada', icon:'✅', effect:'log_event' },
        { label:'Sin acciones', icon:'🚫', effect:'log_event' },
      ],
      showNoOptionsButton:false,
      roundPhasesEnabled:true,
      gamePhases:[
        { id:'player_turn', label:'Turno del jugador', order:1, scope:'turn',
          owner:'player', trigger:'turn_start',
          description:'Usa tus acciones: mover, buscar, atacar, descansar' },
        { id:'crisis_phase', label:'Resolver crisis', order:2, scope:'round',
          owner:'host', trigger:'manual',
          description:'Resolver la crisis de la ronda (cartas de crisis)' },
        { id:'starvation', label:'Hambre y moral', order:3, scope:'round',
          owner:'host', trigger:'manual',
          description:'Consumir comida, bajar moral si no alcanza' },
        { id:'round_cleanup', label:'Cierre de ronda', order:4, scope:'round',
          owner:'host', trigger:'manual',
          description:'Robar carta de objetivo, traición, avanzar marcador' },
      ],
      phaseChecklist:[
        { id:'crisis_resolved', label:'¿Crisis resuelta o penalización aplicada?',
          phaseId:'crisis_phase', required:true, autoReset:'round', visibleTo:'host' },
        { id:'food_consumed', label:'¿Se consumió 1 comida por jugador?',
          phaseId:'starvation', required:true, autoReset:'round', visibleTo:'host' },
        { id:'morale_check', label:'Si no había comida: -1 moral',
          phaseId:'starvation', required:false, autoReset:'round', visibleTo:'host' },
        { id:'betrayal_check', label:'¿Hay traidor? Verificar sabotaje',
          phaseId:'round_cleanup', required:false, autoReset:'round', visibleTo:'host' },
      ],
      externalEntities:[
        { id:'colony_morale', label:'Moral de la colonia', icon:'🏠',
          entityType:'track', stateType:'numeric', defaultState:'8', visibleTo:'all' },
        { id:'food_supply',  label:'Comida restante', icon:'🍖',
          entityType:'resource', stateType:'numeric', defaultState:'10', visibleTo:'all' },
        { id:'active_crisis', label:'Crisis activa', icon:'⚠️',
          entityType:'card', stateType:'status', defaultState:'ninguna', visibleTo:'all' },
      ],
    }
  },

  misionCumplida: {
    id:'mision_cumplida', order:14, name:'Misión Cumplida', emoji:'🎯',
    color:'#00FF9D', category:'card_game', complexity:'low',
    validates:['turns','flow_assistance','turn_timer'],
    valueAdd:['Reloj de ajedrez por jugador','Botón: Resolví una misión','Recordatorio tomar carta','Cooperativo con métricas individuales'],
    config:{
      name:'Misión Cumplida', emoji:'🎯', type:'cooperative',
      cooperativeTeamName:'El Equipo',
      minPlayers:2, maxPlayers:6,
      useRounds:false,
      useTurns:true, turnOrder:'rotative', useFirstPlayerToken:false,
      victoryMode:'manual', manualWinMode:'host_end',
      registers:['wins'],
      playMode:'minimal',
      playObjects:[],
      objectControlScope:'all',
      useFlowAssistance:true,
      turnAssistMode:'agile',
      trackTurnDuration:true,
      showNoOptionsButton:false,
      agileTurnButtons:[
        { label:'Resolví una misión', icon:'🎯', effect:'add_win' },
        { label:'Sin opciones', icon:'🚫', effect:'end_game_loss' },
      ],
      gamePhases:[
        { id:'play_turn', label:'Tu turno', order:1, scope:'turn', owner:'player',
          trigger:'turn_start', description:'Juega cartas, cumple misiones o ayuda a un compañero' },
        { id:'draw_card', label:'Toma una carta', order:2, scope:'turn', owner:'player',
          trigger:'manual', description:'Completa tu mano (4 cartas)' },
      ],
      phaseChecklist:[
        { id:'draw_reminder', label:'Recuerda tomar tu carta del mazo',
          phaseId:'draw_card', required:false, autoReset:'turn', visibleTo:'all' },
      ],
      phaseLifecycle:[
        { id:'draw_life', phaseId:'draw_card', label:'Tomar carta',
          reset:'turn', autoEnter:true, autoExit:false, blocksAdvance:false },
      ],
    }
  },

  falloutShelter: {
    id:'fallout_shelter', order:15, name:'Fallout Shelter', emoji:'☢️',
    color:'#B7FF3C', category:'worker_placement_assist', complexity:'high',
    validates:['turns','phases','entities','checklist'],
    valueAdd:['Turno: colocar moradores','Fases globales: recursos, amenazas, cierre','Entidades: primer jugador, amenaza, habitación'],
    config:{
      name:'Fallout Shelter', emoji:'☢️', type:'individual',
      minPlayers:2, maxPlayers:4,
      useRounds:true, rounds:'libre', roundClose:'manual',
      useTurns:true, turnOrder:'rotative', useFirstPlayerToken:true,
      victoryMode:'points', pointsWinMode:'most',
      registers:['points'],
      playMode:'enhanced',
      playObjects:['score_input','dice_tool'],
      scoreInputLabel:'Ajustar felicidad',
      scoreInputTarget:'points',
      scoreInputAllowNegative:true,
      objectControlScope:'all',
      useTools:true, tools:['dice'],
      useFlowAssistance:true,
      turnAssistMode:'agile',
      trackTurnDuration:false,
      roundPhasesEnabled:true,
      agileTurnButtons:[
        { label:'Listos mis moradores', icon:'👷', effect:'log_event' },
        { label:'Sin moradores', icon:'🚫', effect:'log_event' },
      ],
      gamePhases:[
        { id:'place_dwellers', label:'Colocar moradores', order:1,
          scope:'turn', owner:'player', trigger:'turn_start',
          description:'Coloca tus meeples en habitaciones' },
        { id:'resolve_rooms', label:'Resolver habitaciones', order:2,
          scope:'round', owner:'all', trigger:'all_turns_done',
          description:'Cada jugador cobra recursos según su habitación' },
        { id:'resolve_threat', label:'Resolver amenaza', order:3,
          scope:'round', owner:'host', trigger:'manual',
          description:'Tirar dados de amenaza y aplicar daño' },
        { id:'round_end', label:'Cierre de ronda', order:4,
          scope:'round', owner:'host', trigger:'manual',
          description:'Pasar ficha, reabastecer habitaciones' },
      ],
      phaseChecklist:[
        { id:'rooms_resolved', label:'¿Todos resolvieron su habitación?',
          phaseId:'resolve_rooms', required:true, autoReset:'round', visibleTo:'host' },
        { id:'threat_dice', label:'Tirar dados de amenaza (si hay)',
          phaseId:'resolve_threat', required:false, autoReset:'round', visibleTo:'host' },
        { id:'damage_applied', label:'Aplicar daño/recompensa a jugadores',
          phaseId:'resolve_threat', required:false, autoReset:'round', visibleTo:'host' },
        { id:'token_passed', label:'Pasar ficha de primer jugador',
          phaseId:'round_end', required:false, autoReset:'round', visibleTo:'host' },
        { id:'rooms_restocked', label:'Reabastecer habitaciones/eventos',
          phaseId:'round_end', required:false, autoReset:'round', visibleTo:'host' },
      ],
      externalEntities:[
        { id:'first_player', label:'Primer jugador', icon:'🎯',
          entityType:'token', stateType:'holder', defaultState:'manual', visibleTo:'all' },
        { id:'active_threat', label:'Amenaza activa', icon:'👾',
          entityType:'enemy', stateType:'status', defaultState:'ninguna', visibleTo:'all' },
        { id:'active_room', label:'Habitación activa', icon:'🏠',
          entityType:'room', stateType:'status', defaultState:'manual', visibleTo:'host' },
      ],
      phaseLifecycle:[
        { id:'threat_life', phaseId:'resolve_threat', label:'Resolver amenaza',
          reset:'round', autoEnter:false, autoExit:false, blocksAdvance:true },
      ],
    }
  },

};
