
window.OFFICIAL_PRESETS = {
  strike: {
    id:'strike', order:1, name:'Strike', emoji:'🎲', color:'#9B5DE5', category:'dexterity', complexity:'medium',
    validates:['elimination','rounds','manual_referee','last_alive_auto'],
    valueAdd:['Eliminación rápida','Control de rondas','Historial de derrota','Último vivo gana automático'],
    config:{ name:'Strike', emoji:'🎲', difficulty:'medium', type:'individual', minPlayers:2, maxPlayers:8, useRounds:true, rounds:'libre', roundClose:'manual', useTurns:false, noTurnMode:'mixed', victoryMode:'elimination', elimWinMode:'last_player', registers:['wins'], useElimination:true, playMode:'minimal', playObjects:['defeat_button'], defeatButtonLabel:'Fuera', defeatButtonScope:'round', objectControlScope:'host', trackDefeatReason:true, trackRoundHistory:true, resultActions:[{id:'out_action', label:'Fuera', icon:'💀', color:'#FF3B5C', scope:'round', target:'self', effect:'mark_out', visibleTo:'host', isPrimary:true, prompt:'¿Con cuántos dados quedó?'}], captureActions:[{id:'remaining_dice', label:'Dados restantes', icon:'🎲', color:'#FFD447', captureType:'number', targetRegister:'wins', min:0, max:8, quickValues:[1,2,3,4,5,6,7,8], visibleTo:'host', askAt:'round_end'}], autoBehaviors:[{id:'last_alive_wins', trigger:'player_eliminated', condition:'only_one_active_remains', effect:'declare_round_winner', enabled:true, clearAfter:false, label:'Último vivo gana la ronda'}] }
  },
  cubilete: {
    id:'cubilete', order:2, name:'Cubilete', emoji:'🪙', color:'#FFD447', category:'dice_party', complexity:'medium',
    validates:['rounds','wins','manual_capture','round_questions'],
    valueAdd:['Ganador por ronda','Registro de jugada','Resumen por victoria','Preguntas guiadas'],
    config:{ name:'Cubilete', emoji:'🪙', difficulty:'medium', type:'individual', minPlayers:2, maxPlayers:8, useRounds:true, rounds:'libre', roundClose:'manual', useTurns:true, turnOrder:'rotative', useFirstPlayerToken:true, victoryMode:'wins', winsMode:'most', winsTarget:3, registers:['wins'], captureType:'manual', accumulation:'round', playMode:'minimal', playObjects:['victory_button','first_player_token'], victoryButtonLabel:'Gané', objectControlScope:'host', winConditions:['Carta alta','Par','Dos pares','Tercia','Full','Poker'], trackRoundHistory:true, trackWinnerReason:true, useRoundResolution:true, roundResolutionMode:'guided', roundQuestions:[{id:'hand_type', label:'Tipo de jugada', inputType:'select', options:['Carta alta','Par','Dos pares','Tercia','Full','Poker'], required:true, saveAs:'handType', visibleTo:'host'},{id:'throws_used', label:'¿En cuántas tiradas?', inputType:'select', options:['1','2','3'], required:false, saveAs:'throwsUsed', visibleTo:'host'}], resultActions:[{id:'out_action', label:'Fuera', icon:'💀', color:'#FF3B5C', scope:'round', target:'self', effect:'mark_out', visibleTo:'host', isPrimary:true}], captureActions:[{id:'left_dice', label:'Dados restantes', icon:'🎲', color:'#FFD447', captureType:'number', targetRegister:'wins', min:0, max:5, quickValues:[1,2,3,4,5], visibleTo:'host', askAt:'round_end'}] }
  },
  sushiGoScoreTracker: {
    id:'sushi_go', order:3, name:'Sushi Go', emoji:'🍣', color:'#FF4FA3', category:'card_scoring', complexity:'medium',
    validates:['rounds','manual_score','tiebreak','round_closure'],
    valueAdd:['Captura por ronda','Total acumulado','Desempate claro','Notas por ronda'],
    config:{ name:'Sushi Go', emoji:'🍣', difficulty:'medium', type:'individual', minPlayers:2, maxPlayers:5, useRounds:true, rounds:3, roundClose:'manual', useTurns:false, noTurnMode:'simultaneous', victoryMode:'points', pointsWinMode:'most', pointsValidation:'round_end', registers:['points'], captureType:'manual', accumulation:'global', capturedBy:'host', playMode:'minimal', playObjects:['score_input'], scoreInputLabel:'Capturar puntos', scoreInputTarget:'points', objectControlScope:'host', useRoundResolution:true, roundResolutionMode:'guided', roundQuestions:[{id:'round_points', label:'Puntos de la ronda', inputType:'number', required:true, saveAs:'roundPoints', visibleTo:'host', min:0, max:50},{id:'notes', label:'Notas de ronda', inputType:'text', required:false, saveAs:'roundNotes', visibleTo:'host'}], trackRoundHistory:true }
  },
  uno: {
    id:'uno', order:4, name:'UNO', emoji:'🟥', color:'#FF3B5C', category:'card_party', complexity:'medium',
    validates:['turns','penalties','hand_end','status'],
    valueAdd:['Orden de turno','Penalizaciones','Fin claro de ronda','Estados temporales'],
    config:{ name:'UNO', emoji:'🟥', difficulty:'medium', type:'individual', minPlayers:2, maxPlayers:10, useRounds:true, rounds:'libre', roundClose:'manual', useTurns:true, turnOrder:'rotative', canSkipTurn:true, hasExtraTurns:false, victoryMode:'points', pointsWinMode:'most', pointsValidation:'round_end', targetScore:500, registers:['points'], modifiers:['penalty','bonus'], captureType:'manual', accumulation:'global', capturedBy:'host', playMode:'minimal', playObjects:['score_input'], scoreInputLabel:'Sumar puntos', scoreInputTarget:'points', objectControlScope:'host', resultActions:[{id:'empty_hand', label:'Se quedó sin cartas', icon:'🏁', color:'#00FF9D', scope:'round', effect:'mark_victory', visibleTo:'host', isPrimary:true}], statusIndicators:[{id:'uno_declared', label:'Dijo UNO', icon:'❗', color:'#FFD447', scope:'player', visibility:'all', mode:'toggle', defaultValue:false, durationMode:'manual', clearOn:'none'}], captureActions:[{id:'penalty_cards', label:'Cartas por penalización', icon:'🃏', color:'#FF8A3D', captureType:'number', targetRegister:'points', min:0, max:20, quickValues:[2,4], visibleTo:'host', askAt:'manual'}], trackRoundHistory:true }
  },
  snakesAndLadders: {
    id:'snakes_ladders', order:5, name:'Serpientes y Escaleras', emoji:'🐍', color:'#00FF9D', category:'board_race', complexity:'easy',
    validates:['board_progression','dice','finish_line','capture'],
    valueAdd:['Control de posiciones','Avance por dado','Ganador por meta','Registro de tirada'],
    config:{ name:'Serpientes y Escaleras', emoji:'🐍', difficulty:'easy', type:'individual', minPlayers:2, maxPlayers:6, useRounds:false, useTurns:true, turnOrder:'fixed', useTools:true, tools:['dice'], toolsMode:'informal', toolsRegistered:false, victoryMode:'points', pointsWinMode:'target', targetScore:100, registers:['points'], captureType:'manual', accumulation:'global', playMode:'minimal', playObjects:['score_input'], scoreInputLabel:'Mover casillas', scoreInputTarget:'points', objectControlScope:'all', captureActions:[{id:'dice_result', label:'Resultado del dado', icon:'🎲', color:'#00F5FF', captureType:'number', targetRegister:'points', min:1, max:6, quickValues:[1,2,3,4,5,6], visibleTo:'all', askAt:'manual'}] }
  },
  loteria: {
    id:'loteria', order:6, name:'Lotería', emoji:'🎴', color:'#B7FF3C', category:'simultaneous', complexity:'easy',
    validates:['simultaneous','manual_win','host_control','questions'],
    valueAdd:['Declarar ganador','Control de ronda','Historial simple','Patrón ganador'],
    config:{ name:'Lotería', emoji:'🎴', difficulty:'easy', type:'individual', minPlayers:2, maxPlayers:20, useRounds:true, rounds:'libre', roundClose:'manual', useTurns:false, noTurnMode:'simultaneous', victoryMode:'manual', manualWinMode:'host_end', registers:['wins'], playMode:'minimal', objectControlScope:'host', resultActions:[{id:'loteria_action', label:'¡Lotería!', icon:'🎉', color:'#00FF9D', scope:'round', effect:'mark_victory', visibleTo:'host', isPrimary:true}], useRoundResolution:true, roundResolutionMode:'guided', roundQuestions:[{id:'pattern', label:'Patrón ganador', inputType:'select', options:['Línea','Esquinas','Tabla completa','Centro'], required:false, saveAs:'pattern', visibleTo:'host'}], trackRoundHistory:true }
  },
  jenga: {
    id:'jenga', order:7, name:'Jenga', emoji:'🧱', color:'#FF8A3D', category:'dexterity', complexity:'easy',
    validates:['manual_defeat','elimination','timer','last_alive_auto'],
    valueAdd:['Turnos claros','Quién perdió','Ronda rápida','Último en pie'],
    config:{ name:'Jenga', emoji:'🧱', difficulty:'easy', type:'individual', minPlayers:2, maxPlayers:8, useRounds:true, rounds:'libre', roundClose:'manual', useTurns:true, turnOrder:'rotative', useTimer:true, timerScope:'turn', timerSecs:30, victoryMode:'elimination', elimWinMode:'last_player', useElimination:true, playMode:'minimal', objectControlScope:'host', resultActions:[{id:'tower_fall', label:'Tiró la torre', icon:'💥', color:'#FF3B5C', scope:'round', effect:'mark_out', visibleTo:'host', isPrimary:true}], autoBehaviors:[{id:'last_alive_wins', trigger:'player_eliminated', condition:'only_one_active_remains', effect:'declare_round_winner', enabled:true, clearAfter:false, label:'Último en pie gana'}], trackDefeatReason:true }
  },
  kingOfTokyo: {
    id:'king_of_tokyo', order:8, name:'King of Tokyo', emoji:'👹', color:'#4A90FF', category:'multi_register', complexity:'high',
    validates:['multi_register','dice','elimination','statuses'],
    valueAdd:['Vidas/puntos/energía','Acciones visibles','Control de eliminación','Estados temporales'],
    config:{ name:'King of Tokyo', emoji:'👹', difficulty:'hard', type:'individual', minPlayers:2, maxPlayers:6, useRounds:true, rounds:'libre', roundClose:'manual', useTurns:true, turnOrder:'rotative', victoryMode:'points', pointsWinMode:'target', targetScore:20, registers:['points','custom'], customCounterName:'energía', captureType:'manual', accumulation:'global', modifiers:['bonus','penalty','shield'], useElimination:true, playMode:'enhanced', playObjects:['counter_set','score_input'], scoreInputLabel:'Aplicar cambio', scoreInputTarget:'points', counterSet:[{id:'lives',label:'Vidas',color:'#FF3B5C',icon:'❤️',scope:'player',initialValue:10,min:0,max:10,resetOn:'never',visibleTo:'all'},{id:'energy',label:'Energía',color:'#00F5FF',icon:'⚡',scope:'player',initialValue:0,min:0,max:null,resetOn:'never',visibleTo:'all'}], objectControlScope:'host', useTools:true, tools:['dice'], toolsMode:'informal', toolsRegistered:true, toolsAffect:['score'], resultActions:[{id:'score_victory', label:'Llegó a 20', icon:'🏆', color:'#FFD447', scope:'match', effect:'mark_victory', visibleTo:'host', isPrimary:true},{id:'monster_out', label:'Eliminar', icon:'💀', color:'#FF3B5C', scope:'match', effect:'mark_out', visibleTo:'host', isPrimary:false}], statusIndicators:[{id:'in_tokyo',label:'En Tokyo',icon:'🏙️',color:'#FF8A3D',scope:'player',visibility:'all',mode:'toggle',defaultValue:false,durationMode:'manual',clearOn:'none'},{id:'shielded',label:'Protegido',icon:'🛡️',color:'#4A90FF',scope:'player',visibility:'all',mode:'toggle',defaultValue:false,durationMode:'round',clearOn:'round_end'}] }
  },
  bang: {
    id:'bang', order:9, name:'Bang!', emoji:'🤠', color:'#9B5DE5', category:'hidden_roles', complexity:'high',
    validates:['roles','elimination','asymmetric_goals','status'],
    valueAdd:['Sheriff visible','Vidas y eliminaciones','Historial de roles','Estados visibles'],
    config:{ name:'Bang!', emoji:'🤠', difficulty:'hard', type:'individual', minPlayers:4, maxPlayers:7, useRounds:false, useTurns:true, turnOrder:'rotative', victoryMode:'elimination', elimWinMode:'last_player', useElimination:true, registers:['custom'], customCounterName:'vidas', captureType:'manual', accumulation:'global', roles:['host','player'], scoreCapture:'host', playMode:'minimal', playObjects:['counter_set'], counterSet:[{id:'life',label:'Vida',color:'#FF3B5C',icon:'❤️',scope:'player',initialValue:4,min:0,max:5,resetOn:'never',visibleTo:'all'}], objectControlScope:'host', resultActions:[{id:'bang_out',label:'Eliminar',icon:'💀',color:'#FF3B5C',scope:'match',effect:'mark_out',visibleTo:'host',isPrimary:true}], statusIndicators:[{id:'sheriff',label:'Sheriff',icon:'⭐',color:'#FFD447',scope:'player',visibility:'all',mode:'toggle',defaultValue:false,durationMode:'manual',clearOn:'none'},{id:'jail',label:'En cárcel',icon:'⛓️',color:'#4A90FF',scope:'player',visibility:'all',mode:'toggle',defaultValue:false,durationMode:'turn',clearOn:'turn_end'}], trackDefeatReason:true, trackRoundHistory:true }
  },
  loveLetter: {
    id:'love_letter', order:10, name:'Love Letter', emoji:'💌', color:'#FF4FA3', category:'micro_rounds', complexity:'easy',
    validates:['short_rounds','round_points','elimination_light','status_indicator'],
    valueAdd:['Gana ronda','Puntos acumulados','Cambio rápido','Protección visible'],
    config:{ name:'Love Letter', emoji:'💌', difficulty:'easy', type:'individual', minPlayers:2, maxPlayers:6, useRounds:true, rounds:'libre', roundClose:'manual', useTurns:true, turnOrder:'rotative', victoryMode:'wins', winsMode:'most', winsTarget:4, registers:['wins'], playMode:'minimal', objectControlScope:'host', resultActions:[{id:'round_win',label:'Ganó ronda',icon:'🏆',color:'#FFD447',scope:'round',effect:'mark_victory',visibleTo:'host',isPrimary:true},{id:'knocked_out',label:'Fuera',icon:'💀',color:'#FF3B5C',scope:'round',effect:'mark_out',visibleTo:'host',isPrimary:false}], statusIndicators:[{id:'protected',label:'Protegido',icon:'🛡️',color:'#4A90FF',scope:'player',visibility:'all',mode:'toggle',defaultValue:false,durationMode:'turn',clearOn:'turn_end'}], trackRoundHistory:true }
  },
  coup: {
    id:'coup', order:11, name:'Coup', emoji:'🕶️', color:'#B7FF3C', category:'bluff_roles', complexity:'medium',
    validates:['coins','influence','elimination','status'],
    valueAdd:['Monedas e influencia','Eliminación clara','Turnos limpios','Bloqueos visibles'],
    config:{ name:'Coup', emoji:'🕶️', difficulty:'medium', type:'individual', minPlayers:2, maxPlayers:6, useRounds:false, useTurns:true, turnOrder:'rotative', victoryMode:'elimination', elimWinMode:'last_player', useElimination:true, registers:['custom'], customCounterName:'monedas', captureType:'manual', accumulation:'global', modifiers:['steal','block'], playMode:'enhanced', playObjects:['score_input','counter_set'], scoreInputLabel:'Ajustar monedas', scoreInputTarget:'custom', counterSet:[{id:'influence',label:'Influencia',color:'#FFD447',icon:'🎭',scope:'player',initialValue:2,min:0,max:2,resetOn:'never',visibleTo:'all'}], objectControlScope:'host', resultActions:[{id:'lost_influence',label:'Perdió influencia',icon:'💥',color:'#FF3B5C',scope:'turn',effect:'mark_out',visibleTo:'host',isPrimary:false}], statusIndicators:[{id:'blocked',label:'Bloqueado',icon:'🚫',color:'#4A90FF',scope:'player',visibility:'all',mode:'toggle',defaultValue:false,durationMode:'turn',clearOn:'turn_end'}] }
  },
  familyFeudMx: {
    id:'family_feud_mx', order:12, name:'100 Mexicanos Dijeron', emoji:'💯', color:'#FF8A3D', category:'party_points', complexity:'easy',
    validates:['points','manual_capture','round_closure','teams'],
    valueAdd:['Captura de puntos por respuesta','Cierre claro de ronda','Resumen rápido de equipos','Preguntas guiadas'],
    config:{ name:'100 Mexicanos Dijeron', emoji:'💯', difficulty:'easy', type:'teams', numTeams:2, minPlayers:2, maxPlayers:10, useRounds:true, rounds:'libre', roundClose:'manual', useTurns:false, noTurnMode:'mixed', victoryMode:'points', pointsWinMode:'most', pointsValidation:'round_end', registers:['points'], captureType:'manual', accumulation:'global', capturedBy:'host', playMode:'minimal', playObjects:['score_input'], scoreInputLabel:'Sumar puntos', scoreInputTarget:'points', objectControlScope:'host', useRoundResolution:true, roundResolutionMode:'guided', roundQuestions:[{ id:'answer_points', label:'Puntos logrados en la respuesta', inputType:'number', required:true, saveAs:'answerPoints', visibleTo:'host', min:0, max:100 },{ id:'board_clean', label:'¿Se limpió el tablero?', inputType:'select', options:['Sí','No'], required:false, saveAs:'boardClean', visibleTo:'host' }], resultActions:[{id:'stole_board',label:'Robó tablero',icon:'⚡',color:'#FFD447',scope:'round',effect:'record_only',visibleTo:'host',isPrimary:false}], trackRoundHistory:true, trackWinnerReason:true }
  },
  yahtzee: {
    id:'yahtzee', order:13, name:'Yahtzee', emoji:'🎯', color:'#FF8A3D', category:'score_sheet', complexity:'high',
    validates:['score_sheet','dice','category_capture','round_questions'],
    valueAdd:['Hoja de puntaje','Totales claros','Rondas por categoría','Captura guiada'],
    config:{ name:'Yahtzee', emoji:'🎯', difficulty:'hard', type:'individual', minPlayers:1, maxPlayers:6, useRounds:true, rounds:13, roundClose:'manual', useTurns:true, turnOrder:'rotative', victoryMode:'points', pointsWinMode:'most', pointsValidation:'round_end', registers:['points'], captureType:'manual', accumulation:'global', playMode:'enhanced', objectControlScope:'self', useTools:true, tools:['dice'], toolsMode:'informal', useRoundResolution:true, roundResolutionMode:'guided', roundQuestions:[{id:'category',label:'Categoría elegida',inputType:'select',options:['1s','2s','3s','4s','5s','6s','Three of a Kind','Four of a Kind','Full House','Small Straight','Large Straight','Yahtzee','Chance'],required:true,saveAs:'category',visibleTo:'self'},{id:'category_points',label:'Puntos de la categoría',inputType:'number',required:true,saveAs:'categoryPoints',visibleTo:'self',min:0,max:50}] }
  },
  blackjack: {
    id:'blackjack', order:13, name:'Blackjack', emoji:'🂡', color:'#4A90FF', category:'dealer_flow', complexity:'medium',
    validates:['dealer_control','manual_points','round_winner'],
    valueAdd:['Ganador por mano','Control del dealer','Historial por mano'],
    config:{ name:'Blackjack', emoji:'🂡', type:'individual', minPlayers:2, maxPlayers:7, useRounds:true, rounds:'libre', roundClose:'manual', useTurns:true, turnOrder:'fixed', victoryMode:'wins', winsMode:'most', winsTarget:5, registers:['wins','points'], captureType:'manual', accumulation:'round', capturedBy:'host', playMode:'minimal', playObjects:['victory_button','score_input','round_resolution_popup'], victoryButtonLabel:'Ganó la mano', scoreInputLabel:'Capturar mano', scoreInputTarget:'points', roundResolutionFields:['winner','round_points','notes'], objectControlScope:'host', trackRoundHistory:true }
  }
};
